apiVersion : apps/v1
kind: Deployment
metadata:
  name: petstoreservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstoreservice
  template:
    metadata:
      labels:
        app: petstoreservice 
    spec:
      containers:
        - name: petstoreservice 
          image: petstore17.azurecr.io/petstoreservice
          ports:
          - containerPort: 80